worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    error_log   /var/log/nginx/error.log warn;

    sendfile        on;
    keepalive_timeout  65;

    # Upstream definitions (optional)
    upstream auth_service {
        server authservice:2000;
    }

    upstream profile_service {
        server profileservice:2001;
    }

    upstream task_service {
        server taskservice:2002;
    }

    # upstream class-service {
    #     server taskservice:2002;
    # }

    server {
        listen 80;
        server_name localhost;

        # Reverse proxy cho Auth Service
        location /api/auth/ {
            proxy_pass http://auth_service/;
            
        }

        # Reverse proxy cho Profile Service
        location /api/profile/ {
            proxy_pass http://profile_service/;
            
            # Forward toàn bộ headers, bao gồm cả Authorization
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_request_headers on;
        }

        # Reverse proxy cho Task Service
        location /api/task/ {
            proxy_pass http://task_service/;

            # Forward toàn bộ headers, bao gồm cả Authorization
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_request_headers on;
        }

        

        # Default fallback
        location / {
            return 404;
        }
    }
}
